[package]
name = "wasm_regex"
version = "0.1.0"
edition = "2018"
crate-type = ["cdylib"]

[dependencies]
regex = "1.5"
js-sys = "0.3"

[dependencies.wasm-bindgen]
version = "0.2"
features = ["serde-serialize"]

[profile.release]
lto = true
opt-level = "z"

[lib]
crate-type = ["cdylib", "rlib"]
